from ast import Str
from random import choices
import re
import shutil
from nextcord.ext import commands
import nextcord
from nextcord import Interaction, SlashOption
import requests
from typing import List
from bs4 import BeautifulSoup

from utils import Embed, Colors

from main import TESTING_GUILD_ID

class User(commands.Cog):
    TESTING_GUILD_ID = 0
    def __init__(self, client, color, auth):
        self.client = client
        self.color = color
        self.auth = auth

    @nextcord.slash_command(name="randomuser", description="Generate a random user profile", guild_ids=TESTING_GUILD_ID)
    async def randomuser(self, interaction: Interaction):
        r = requests.get('https://randomuser.me/api/?nat=us')
        data = r.json()
        user = data['results'][0]
        e = Embed.make_embed(self,  
        title=user['name']['first'] + " " + user['name']['last'], 
        description="", color=Colors.purple, 
        image_url=user['picture']['large'], 
        thumbnail="https://patch.com/img/cdn20/users/22973312/20190703/111508/styles/patch_image/public/green-check-point-patch___03111500060.jpg?width=695&height=695&fit=crop&crop=faces&auto=format&q=100", 
        footer_text="Generated by randomuser.me", 
        fields=[{"name": "Phone Number", "value": user["phone"], 
        "inline": False}, {"name": "Email", "value": user["email"], "inline": False}, {"name": "Address", 
        "value": f'{user["location"]["street"]["number"]} {user["location"]["street"]["name"]}, {user["location"]["city"]}, {user["location"]["state"]}, {user["location"]["postcode"]}', "inline": False}])
        await interaction.send(embed=e)

    @nextcord.slash_command(name="pick", guild_ids=TESTING_GUILD_ID)
    async def choose_a_number(
        interaction: Interaction,
        number: int = SlashOption(
            name="picker",
            description="The number you want",
            choices={"one": 1, "two": 2, "three": 3},
        ),
    ):
        await interaction.response.send_message(f"You chose {number}!")

    @nextcord.slash_command(name="hi", guild_ids=TESTING_GUILD_ID)
    async def hi(
        interaction: Interaction,
        member: nextcord.Member = SlashOption(name="user", description="User to say hi to"),
    ):
        await interaction.response.send_message(
            f"{interaction.user} just said hi to {member.mention}"
    )
    @nextcord.slash_command(name="fakeperson", description="Generate a fake person", guild_ids=TESTING_GUILD_ID)
    async def fakeperson(self, interaction: Interaction, version: int = SlashOption(name="version", 
    description="Version of the fake person AI", 
    choices={"Version 1": 1, "Version 2": 2},
    required=True,
    verify=True)):
        url = f'https://boredhumans.com/api_faces{"" if version == 1 else "2"}.php'
        r = requests.get(url)
        data = r.text
        soup = BeautifulSoup(data, 'html.parser')
        await interaction.send(soup.find('img')['src'])
   

def setup(client, **kwargs):
    print(f"Loaded command: {__name__}")
    client.add_cog(User(client, **kwargs))

    